server:
  port: 8762
eureka:
  instance:
    hostname: localhost2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost1:8761/eureka,http://localhost3:8763/eureka
spring:
  application:
    name: eureka-server2