server:
  port: 8081
spring:
  application:
    name: criteria-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: xuhaixing
    password: xuhaixing
    url: jdbc:mysql://192.168.94.151:3306/mytest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true