server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: zuul-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
zuul:
  routes:
    api-a:
      path: /feign/**
      service-id: eureka-feign
      retryable: true
#zuul:
    #ºöÂÔÄ³¸öÎ¢·şÎñ
#  ignored-services: eureka-feign

#zuul:
#  routes:
#    eureka-feign: /feign/**
#zuul:
#  routes:
#    api-a:
#      path: /feign/**
#      service-id: eureka-feign
#zuul:
#  routes:
#    feign:
#      path: /feign/**
#      url: http://localhost:8085/
