server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: zuul-service

#zuul:
    #忽略某个微服务
#  ignored-services: eureka-feign

#zuul:
#  routes:
#    eureka-feign: /feign/**
#zuul:
#  routes:
#    api-a:
#      path: /feign/**
#      service-id: eureka-feign
#zuul:
#  routes:
#    feign:
#      path: /feign/**
#      url: http://localhost:8085/
