spring:
  application:
    name: user-service
  zipkin:
    base-url: http://192.168.94.151:9411
    #discovery-client-enabled: true
   # service:
      #name: zipkin-service
    enabled: true
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://locahost:8761/eureka
feign:
  hystrix:
    enabled: true
