server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/
spring:
  application:
    name: eureka-client
#通过配置文件方式配置自定义ribbon client
eureka-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
