spring:
  redis:
    host: 192.168.94.151
    port: 6379
    password: xuhaixing
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        min-idle: 0
    timeout: 5000