server:
  port: 8080
  tomcat:
    accept-count: 100
    max-threads: 100
    max-connections: 100
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
zuul:
  routes:
    api-a:
      path: /user/**
      service-id: ms-user
  host:
    max-per-route-connections: 100
    max-total-connections: 500
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 500