server:
  port: 8083
  tomcat:
    max-threads: 500
    max-connections: 2000
    accept-count: 2000
spring:
  application:
    name: ms-user
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1/eureka